# 🖥️ Video / display
fullscreen=yes
screen=1
force-window=yes
vo=gpu
hwdec=auto
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation=yes
autofit=100%

# 🎞️ Playback behavior
keep-open=yes
loop=yes
watch-later-options=sid
volume=75

# 🎹 IPC (for external control)
input-ipc-server=/tmp/mpvsocket

# 🎨 Subtitles
sub-ass-override=yes
sub-color=1.0/0.9/0.4
sub-border-color=0.0/0.0/0.0
sub-border-size=5
sub-font-size=55
sub-bold=yes
sub-font=Roboto
sub-ass-use-video-data=all
sub-auto=fuzzy
sub-file-paths=.

# 🌐 Language preferences
alang=jpn,japanese,en,eng
slang=en,eng,ru,rus,russian

# Screenshots
screenshot-template=%F_%p_%04n
